name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Run a one-line script (you can keep or modify this as needed)
      - name: Run a one-line script
        run: echo Hello, world!

      # Run a multi-line script (you can keep or modify this as needed)
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Run your script that requires the API key
      - name: Run Script with API Key
        env:
          API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}  # Reference your secret here
        run: |
          # Replace with your actual script that uses the API key
          python config.py

